modLoader = "javafml"
loaderVersion = "[32,)"
license = "MIT"

[[mods]]
modId = "seafarer"
version = "${file.jarVersion}"
logoFile = "seafarer.png"
authors = "Barl Incorporated"
displayName = "Seafarer"
description = '''Explore the seas, conquer the seas!'''

[[dependencies.seafarer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.seafarer]]
modId = "forge"
mandatory = true
versionRange = "[47.1.3,)"
ordering = "AFTER"
side = "BOTH"